# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tasksHistory(object):
    def setupUi(self, tasksHistory):
        tasksHistory.setObjectName("tasksHistory")
        tasksHistory.resize(948, 625)
        self.tableWidget = QtWidgets.QTableWidget(tasksHistory)
        self.tableWidget.setGeometry(QtCore.QRect(30, 40, 891, 531))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setHighlightSections(True)

        self.retranslateUi(tasksHistory)
        QtCore.QMetaObject.connectSlotsByName(tasksHistory)

    def retranslateUi(self, tasksHistory):
        _translate = QtCore.QCoreApplication.translate
        tasksHistory.setWindowTitle(_translate("tasksHistory", "История "))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("tasksHistory", "Задача"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("tasksHistory", "id задачи"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("tasksHistory", "Адресс заказчика"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("tasksHistory", "Адресс исполнителя"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("tasksHistory", "Стоимость"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("tasksHistory", "Статус"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("tasksHistory", "Заголовок"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("tasksHistory", "Описание"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tasksHistory = QtWidgets.QWidget()
    ui = Ui_tasksHistory()
    ui.setupUi(tasksHistory)
    tasksHistory.show()
    sys.exit(app.exec_())
