# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ok.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_isOk(object):
    def setupUi(self, isOk):
        isOk.setObjectName("isOk")
        isOk.resize(376, 224)
        self.label = QtWidgets.QLabel(isOk)
        self.label.setGeometry(QtCore.QRect(110, 50, 211, 71))
        self.label.setObjectName("label")
        self.okBtn = QtWidgets.QPushButton(isOk)
        self.okBtn.setGeometry(QtCore.QRect(110, 130, 141, 28))
        self.okBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.okBtn.setObjectName("okBtn")

        self.retranslateUi(isOk)
        QtCore.QMetaObject.connectSlotsByName(isOk)

    def retranslateUi(self, isOk):
        _translate = QtCore.QCoreApplication.translate
        isOk.setWindowTitle(_translate("isOk", "ОК"))
        self.label.setText(_translate("isOk", "Операция выполнена !"))
        self.okBtn.setText(_translate("isOk", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    isOk = QtWidgets.QDialog()
    ui = Ui_isOk()
    ui.setupUi(isOk)
    isOk.show()
    sys.exit(app.exec_())
