# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_reg(object):
    def setupUi(self, reg):
        reg.setObjectName("reg")
        reg.resize(723, 506)
        self.groupBox = QtWidgets.QGroupBox(reg)
        self.groupBox.setGeometry(QtCore.QRect(50, 80, 261, 271))
        self.groupBox.setObjectName("groupBox")
        self.regNick = QtWidgets.QLineEdit(self.groupBox)
        self.regNick.setGeometry(QtCore.QRect(80, 50, 113, 22))
        self.regNick.setObjectName("regNick")
        self.regLogin = QtWidgets.QLineEdit(self.groupBox)
        self.regLogin.setGeometry(QtCore.QRect(80, 100, 113, 22))
        self.regLogin.setText("")
        self.regLogin.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.regLogin.setObjectName("regLogin")
        self.regPwd = QtWidgets.QLineEdit(self.groupBox)
        self.regPwd.setGeometry(QtCore.QRect(80, 150, 113, 22))
        self.regPwd.setText("")
        self.regPwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.regPwd.setObjectName("regPwd")
        self.regButton = QtWidgets.QPushButton(self.groupBox)
        self.regButton.setGeometry(QtCore.QRect(70, 190, 131, 28))
        self.regButton.setObjectName("regButton")
        self.groupBox_2 = QtWidgets.QGroupBox(reg)
        self.groupBox_2.setGeometry(QtCore.QRect(390, 80, 261, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.logLogin = QtWidgets.QLineEdit(self.groupBox_2)
        self.logLogin.setGeometry(QtCore.QRect(80, 80, 113, 22))
        self.logLogin.setText("")
        self.logLogin.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.logLogin.setObjectName("logLogin")
        self.logPwd = QtWidgets.QLineEdit(self.groupBox_2)
        self.logPwd.setGeometry(QtCore.QRect(80, 130, 113, 22))
        self.logPwd.setText("")
        self.logPwd.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.logPwd.setObjectName("logPwd")
        self.logButton = QtWidgets.QPushButton(self.groupBox_2)
        self.logButton.setGeometry(QtCore.QRect(70, 190, 131, 28))
        self.logButton.setObjectName("logButton")

        self.retranslateUi(reg)
        QtCore.QMetaObject.connectSlotsByName(reg)

    def retranslateUi(self, reg):
        _translate = QtCore.QCoreApplication.translate
        reg.setWindowTitle(_translate("reg", "Регистрация/логин"))
        self.groupBox.setTitle(_translate("reg", "Регистрация"))
        self.regNick.setPlaceholderText(_translate("reg", "Ник"))
        self.regLogin.setPlaceholderText(_translate("reg", "Адресс Аккаунта"))
        self.regPwd.setPlaceholderText(_translate("reg", "Пароль"))
        self.regButton.setText(_translate("reg", "Зарегистрироваться"))
        self.groupBox_2.setTitle(_translate("reg", "Логин"))
        self.logLogin.setPlaceholderText(_translate("reg", "Адресс Аккаунта"))
        self.logPwd.setPlaceholderText(_translate("reg", "Пароль"))
        self.logButton.setText(_translate("reg", "Логин"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    reg = QtWidgets.QDialog()
    ui = Ui_reg()
    ui.setupUi(reg)
    reg.show()
    sys.exit(app.exec_())
